Repository aimclub/Edulytica, pull requests merged in 2024-06, with the labels that each got.

#14 Refactored EAF-D-1 to PROC
  .codecov.yml
  .github/workflows/build-test.yml
  requirements.txt
  src/data_handling/ISU_parser.py
  src/data_handling/__init__.py
  src/data_handling/isu-env-example
  src/data_handling/persons-example.json
  src/data_handling/persons-structure.json
Labels: refactor

#15 PROC-VKRsParsing to PROC: Add ParserVKR Class for Parsing VKR Files
  src/data_handling/VKR_parser.py
Labels: enhancement

#17 PROC-ExtractJson to PROC: Add DataManager Class for ISU data handling
  requirements.txt
  src/data_handling/data_manager.py
  src/data_handling/stop_words.txt
  src/data_handling/Оценка_Релевантности_неструктурированных_данных.ipynb
  tests/data_handling/__init__.py
  tests/data_handling/test_data_manager.py
  tests/data_handling/test_persons.json
Labels: enhancement

#19 [fix]: fix build-test.yml file
  .github/workflows/build-test.yml
Labels: fix

#20 file added extraction.py
  src/extraction.ipynb
  src/requirements.txt
Labels: documentation, good first issue

#18 PROC-ExtractPDF to PROC: Add PDFParser Class for VKR files extracting to csv
  requirements.txt
  src/data_handling/pdf_parser.py
  tests/data_handling/test_dir/test.pdf
  tests/data_handling/test_pdf_parser.py
Labels: enhancement

#25 Add tests for VKRs parser
  tests/data_handling/test_VKR_parser.py
  tests/data_handling/test_pdf_parser.py
Labels: tests

#26 Write an algorithm to calculate the percentage of changes in the text
  src/algorithms/TextComparator.py
  tests/algorithms/testTextComparator.py
Labels: enhancement

#27 PROC to development: added tests for data_handling
  .codecov.yml
  tests/data_handling/test_VKR_parser.py
  tests/data_handling/test_pdf_parser.py
Labels: tests

#30 [feat]: updated readme
  README.md
Labels: documentation

#31 CodeCov-Fix to dev: fixed tests
  .codecov.yml
  .github/workflows/build-test.yml
  README.md
  requirements.txt
  src/algorithms/TextComparator.py
  tests/algorithms/__init__.py
  tests/algorithms/test_TextComparator.py
  tests/data_handling/test_ISU_parser.py
  tests/data_handling/test_VKR_parser.py
  tests/data_handling/test_data_manager.py
  tests/data_handling/test_pdf_parser.py
  tests/parsing/test_file_parsing.py
  tests/preprocessing/test_preprocessing.py
Labels: fix, tests
