Repository aimclub/Edulytica, pull requests merged in 2025-05, with the labels that each got.

#207 [E-205]: Integrate authorization block with Backend
  src/front_end/Dockerfile
  src/front_end/package-lock.json
  src/front_end/package.json
  src/front_end/src/App.jsx
  src/front_end/src/api/axios.api.js
  src/front_end/src/components/header/header.jsx
  src/front_end/src/components/profileModal/profileModal.jsx
  src/front_end/src/components/registrationForm/registrationForm.jsx
  src/front_end/src/pages/account/account.jsx
  src/front_end/src/pages/home/home.jsx
  src/front_end/src/pages/registration/registration.jsx
  src/front_end/src/routes/AppRoutes.jsx
  src/front_end/src/services/auth.service.js
  src/front_end/src/store/authSlice.js
  src/front_end/src/utils/validation/validationUtils.js
  src/front_end/tests/validationUtils.test.js
Labels: Frontend

#200 [E-79]: Added RAG module
  requirements.txt
  src/rag/README.md
  src/rag/__init__.py
  src/rag/config/config.yaml
  src/rag/const.py
  src/rag/core/chroma_db/__init__.py
  src/rag/core/chroma_db/chroma_manager.py
  src/rag/core/embedder/__init__.py
  src/rag/core/embedder/embedding_processor.py
  src/rag/core/event_specifics/__init__.py
  src/rag/core/event_specifics/event_finder.py
  src/rag/core/prompt_enricher/__init__.py
  src/rag/core/prompt_enricher/prompt_enricher.py
  src/rag/core/text_processor/__init__.py
  src/rag/core/text_processor/text_processor.py
  src/rag/core/utils/config_loader.py
  src/rag/data/Specification.xlsx
  src/rag/data/article_2.txt
  src/rag/docker-compose.yml
  src/rag/docs/rag_sequnce.png
  src/rag/example/example.ipynb
  src/rag/llm/LanguageModelClient.py
  src/rag/llm/__init__.py
  src/rag/pipeline.py
  src/rag/requirements.txt
  src/rag/semantic_search/ChromaSearcher.py
  src/rag/semantic_search/SemanticSearcher.py
  src/rag/semantic_search/__init__.py
  src/rag/utils/FileParser.py
  src/rag/utils/TextProcessingUtils.py
  src/rag/utils/__init__.py
  tests/parsing/__init__.py
  tests/parsing/files/test.docx
  tests/parsing/files/test.odt
  tests/parsing/files/test.pdf
  tests/parsing/test_file_parsing.py
  tests/preprocessing/__init__.py
  tests/preprocessing/test_preprocessing.py
  tests/rag/test_event_finder.py
  tests/rag/test_pipeline.py
  tests/rag/test_prompt_enricher.py
  tests/rag/test_text_processor.py
Labels: RAG

#208 [E-193]: Create exeption folder and add QuantizationExeption
  examples/LLM_use_example.py
  examples/llm_use_example.py
  examples/rag_example.py
  pytest.ini
  src/LLM/__init__.py
  src/LLM/qwen/__init__.py
  src/LLM/vikhr/__init__.py
  src/common/database/crud/custom_event_crud.py
  src/common/database/crud/event_crud.py
  src/common/database/crud/ticket_type_crud.py
  src/edulytica_api/alembic/versions/d8d3c0658591_drop_unique_index_on_users_email.py
  src/edulytica_api/routers/account.py
  src/edulytica_api/routers/actions.py
  src/edulytica_api/schemas/account_schemas.py
  src/exeptions/llm/quantization_exeption.py
  src/llm/__init__.py
  src/llm/model_instruct.py
  src/llm/model_interface.py
  src/llm/model_pipeline.py
  src/llm/qwen/__init__.py
  src/llm/qwen/qwen_instruct.py
  src/llm/qwen/qwen_instruct_pipeline.py
  src/llm/utils.py
  src/llm/vikhr/__init__.py
  src/llm/vikhr/vikhr_nemo_instruct.py
  src/llm/vikhr/vikhr_nemo_instruct_pipeline.py
  src/models/Dockerfile
  src/models/app.py
  src/models/routers/llm_models.py
  src/orchestration/Dockerfile
  src/orchestration/app.py
  src/rag/Dockerfile
  src/rag/app.py
  src/rag/routers/rag.py
  tests/.test_env
  tests/api/conftest.py
  tests/api/test_api_account.py
  tests/api/test_api_actions.py
  tests/api/test_api_auth.py
  tests/api/test_api_auth_integration.py
  tests/common/auth/test_auth_bearer.py
  tests/common/auth/test_auth_utils.py
  tests/common/utils/test_logger.py
  tests/common/utils/test_utils.py
Labels: fix

#212 [E-211]: Integrate profile and edditing profile modal with Backend
  src/edulytica_api/routers/account.py
  src/front_end/src/App.jsx
  src/front_end/src/api/axios.api.js
  src/front_end/src/components/addFile/addFile.jsx
  src/front_end/src/components/editingProfile/editingProfile.jsx
  src/front_end/src/components/editingProfile/editingProfile.scss
  src/front_end/src/components/profileModal/profileModal.jsx
  src/front_end/src/components/registrationForm/registrationForm.jsx
  src/front_end/src/index.jsx
  src/front_end/src/pages/account/account.jsx
  src/front_end/src/services/auth.service.js
  src/front_end/src/store/authSlice.js
  src/front_end/src/utils/validateToken.js
  src/front_end/src/utils/validation/validationUtils.js
Labels: Frontend
