Repository aimclub/Edulytica, pull requests merged in 2025-03, with the labels that each got.

#104 [E-64] Update the current state of the web application
  .gitignore
  alembic.ini
  alembic/README
  alembic/env.py
  alembic/script.py.mako
  docker-compose-database.yml
  requirements.txt
  src/edulytica_api/Wiki/account.md
  src/edulytica_api/Wiki/actions.md
  src/edulytica_api/Wiki/auth.md
  src/edulytica_api/app.py
  src/edulytica_api/auth/auth_bearer.py
  src/edulytica_api/auth/helpers/utils.py
  src/edulytica_api/auth/helpers/validators.py
  src/edulytica_api/crud/factory.py
  src/edulytica_api/crud/result_files_crud.py
  src/edulytica_api/crud/tickets_crud.py
  src/edulytica_api/crud/token_crud.py
  src/edulytica_api/crud/user_crud.py
  src/edulytica_api/database.py
  src/edulytica_api/helpers/utils.py
  src/edulytica_api/helpers/validators.py
  src/edulytica_api/models/__init__.py
  src/edulytica_api/models/models.py
  src/edulytica_api/models/updated_models.py
  src/edulytica_api/routers/auth.py
  src/edulytica_api/routers/llm_services.py
  src/edulytica_api/routers/norm_services.py
  src/edulytica_api/schemas/__init__.py
  src/edulytica_api/schemas/cropped_schemas.py
  src/edulytica_api/schemas/system_schemas.py
  src/edulytica_api/utils/logger.py
  src/edulytica_api/utils/moscow_datetime.py
Labels: Backend

#108 [E-90] Implement docker-compose for backend services
  .gitattributes
  .gitignore
  alembic.ini
  docker-compose-database.yml
  docker-compose.yml
  src/edulytica_api/Dockerfile
  src/edulytica_api/alembic/README
  src/edulytica_api/alembic/env.py
  src/edulytica_api/alembic/script.py.mako
  src/edulytica_api/alembic/versions/018c20e341ef_initial_migration.py
  src/edulytica_api/docker-entrypoint.sh
  src/edulytica_api/models/init_models.py
  src/edulytica_api/requirements.txt
  src/front_end/Dockerfile
  src/front_end/package-lock.json
  src/front_end/package.json
  src/front_end/public/index.html
  src/front_end/src/components/App.js
  src/front_end/src/components/DetailResult.js
  src/front_end/src/components/Header.js
  src/front_end/src/components/LLMForms.js
  src/front_end/src/components/Layout.js
  src/front_end/src/components/LoginForm.js
  src/front_end/src/components/Logout.js
  src/front_end/src/components/Results.js
  src/front_end/src/css/detail_result.css
  src/front_end/src/css/headers.css
  src/front_end/src/css/index.css
  src/front_end/src/css/main.css
  src/front_end/src/css/results_list.css
  src/front_end/src/css/upload.css
  src/front_end/src/images/logo.svg
  src/front_end/src/index.js
  src/front_end/src/provider/authProvider.js
  src/front_end/src/provider/jwtInterceptor.js
  src/front_end/src/routes/ProtectedRoute.js
  src/front_end/src/routes/Routes.js
Labels: Backend

#124 [fix]: Updated badges
  .github/workflows/documentation.yml
  README.md
Labels: Repo

#126 [E-122]: updated codecov section in workflow
  .github/workflows/build-test.yml
Labels: Repo

#125 [E-105] Added ChromaDB in docker-compose
  docker-compose.yml
Labels: RAG

#131 [E-115/116/117/118]: updated the base pages on the client
  .gitignore
  src/front_end/package-lock.json
  src/front_end/package.json
  src/front_end/public/index.html
  src/front_end/src/App.jsx
  src/front_end/src/assets/css/global.scss
  src/front_end/src/assets/fonts/SF-Pro-Display-Semibold.woff
  src/front_end/src/assets/fonts/SFPRODISPLAYBOLD.woff
  src/front_end/src/assets/fonts/SFPRODISPLAYMEDIUM.woff
  src/front_end/src/assets/fonts/SFPRODISPLAYREGULAR.woff
  src/front_end/src/assets/images/logo.svg
  src/front_end/src/components/App.js
  src/front_end/src/components/DetailResult.js
  src/front_end/src/components/Header.js
  src/front_end/src/components/LLMForms.js
  src/front_end/src/components/Layout.js
  src/front_end/src/components/LoginForm.js
  src/front_end/src/components/Logout.js
  src/front_end/src/components/Results.js
  src/front_end/src/components/accountModal/accountModal.jsx
  src/front_end/src/components/accountModal/accountModal.scss
  src/front_end/src/components/addFile/addFile.jsx
  src/front_end/src/components/addFile/addFile.scss
  src/front_end/src/components/header/header.jsx
  src/front_end/src/components/header/header.scss
  src/front_end/src/components/profileModal/profileModal.jsx
  src/front_end/src/components/profileModal/profileModal.scss
  src/front_end/src/components/registrationForm/registrationForm.jsx
  src/front_end/src/components/registrationForm/registrationForm.scss
  src/front_end/src/css/detail_result.css
  src/front_end/src/css/headers.css
  src/front_end/src/css/index.css
  src/front_end/src/css/main.css
  src/front_end/src/css/results_list.css
  src/front_end/src/css/upload.css
  src/front_end/src/index.js
  src/front_end/src/index.jsx
  src/front_end/src/pages/account/account.jsx
  src/front_end/src/pages/account/account.scss
  src/front_end/src/pages/home/home.jsx
  src/front_end/src/pages/home/home.scss
  src/front_end/src/pages/registration/registration.jsx
  src/front_end/src/pages/registration/registration.scss
  src/front_end/src/provider/authProvider.js
  src/front_end/src/provider/jwtInterceptor.js
  src/front_end/src/routes/AppRoutes.jsx
  src/front_end/src/routes/ProtectedRoute.js
  src/front_end/src/routes/Routes.js
  src/front_end/src/utils/button/buttonSubmit.jsx
  src/front_end/src/utils/button/buttonSubmit.scss
  src/front_end/src/utils/input/input.jsx
  src/front_end/src/utils/input/input.scss
Labels: Frontend

#145 [E-58-2]: Update the CI/CD repository with test runs, bots and other analyzers #2 (pep8 var)
  .github/workflows/autopep8.yml
  .github/workflows/build-test.yml
  .github/workflows/documentation.yml
  .github/workflows/fix-pep8-command.yml
  .github/workflows/slash-command-dispatch.yml
  .gitignore
  .pep8
  .pep8ignore
  .pep8speaks.yml
Labels: Repo

#154 [E-153]: file attachment functionality
  src/front_end/src/App.jsx
  src/front_end/src/components/accountModal/accountModal.jsx
  src/front_end/src/components/addFile/addFile.jsx
  src/front_end/src/components/addFile/addFile.scss
  src/front_end/src/components/eventModal/eventModal.jsx
  src/front_end/src/components/eventModal/eventModal.scss
  src/front_end/src/pages/account/account.jsx
  src/front_end/src/routes/AppRoutes.jsx
Labels: Frontend

#123 [E-67] Review the system user role map
  docs/conf.py
  examples/pdf_parsing_example.py
  examples/rag_example.py
  examples/vkr_parsing_example.py
  src/algorithms/TextComparator.py
  src/data_handling/PDFParser.py
  src/data_handling/VKRParser.py
  src/edulytica_api/Wiki/actions.md
  src/edulytica_api/__init__.py
  src/edulytica_api/alembic/versions/e68f981950f8_add_default_role_and_statuses.py
  src/edulytica_api/app.py
  src/edulytica_api/auth/auth_bearer.py
  src/edulytica_api/auth/helpers/utils.py
  src/edulytica_api/celery/celeryconfig.py
  src/edulytica_api/celery/tasks.py
  src/edulytica_api/crud/base/factory.py
  src/edulytica_api/crud/document_crud.py
  src/edulytica_api/crud/document_report_crud.py
  src/edulytica_api/crud/document_summary_crud.py
  src/edulytica_api/crud/result_files_crud.py
  src/edulytica_api/crud/ticket_status_crud.py
  src/edulytica_api/crud/tickets_crud.py
  src/edulytica_api/crud/token_crud.py
  src/edulytica_api/crud/user_crud.py
  src/edulytica_api/crud/user_role_crud.py
  src/edulytica_api/llms/llm_model.py
  src/edulytica_api/models/models.py
  src/edulytica_api/models/updated_models.py
  src/edulytica_api/parser/Elem.py
  src/edulytica_api/parser/Parser.py
  src/edulytica_api/routers/auth.py
  src/edulytica_api/routers/llm_services.py
  src/edulytica_api/schemas/__init__.py
  src/edulytica_api/schemas/cropped_schemas.py
  src/edulytica_api/schemas/llm_schema.py
  src/edulytica_api/schemas/system_schemas.py
  src/edulytica_api/utils/default_enums.py
  src/edulytica_api/utils/logger.py
  src/extracting_rules/extract.py
  src/extracting_rules/helpers/DocumentFormatter.py
  src/extracting_rules/models/GeminiModel.py
  src/extracting_rules/models/GigaModel.py
  src/extracting_rules/models/OpenModel.py
  src/rag/const.py
  src/rag/semantic_search/SemanticSearcher.py
  src/rag/utils/TextProcessingUtils.py
  tests/algorithms/test_TextComparator.py
  tests/data_handling/test_pdf_parser.py
  tests/data_handling/test_vkr_parser.py
  tests/parsing/test_file_parsing.py
  tests/preprocessing/test_preprocessing.py
Labels: Backend

#156 [E-120]: Implement screens with the results of working with documents
  .codecov.yml
  .pep8ignore
  src/front_end/src/components/accountModal/accountModal.jsx
  src/front_end/src/components/addFile/addFile.jsx
  src/front_end/src/components/eventModal/eventModal.jsx
  src/front_end/src/components/resultFile/resultFile.jsx
  src/front_end/src/components/resultFile/resultFile.scss
  src/front_end/src/components/resultFile/text.js
  src/front_end/src/pages/account/account.jsx
  src/front_end/src/routes/AppRoutes.jsx
Labels: Frontend
